#!/bin/bash

# Run the `./deploy` command from the project directory to deploy the project files to the Pi.

STARTTIME=$(date +%s%3N)

if [ "$1" = "init" ]; then
  echo "Initalizing ssh key..."
  ssh-keygen -t rsa -b 2048
  ssh-copy-id pi@10.18.16.16
fi

ssh pi@10.18.16.16 'rw; rm -rf /home/pi/GreenVision/*'
scp ./* pi@10.18.16.16:~/GreenVision/
ssh pi@10.18.16.16 'ro'

echo "Finished deploying in $(($(date +%s%3N) - $STARTTIME)) ms"
